//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace join
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputOrders
    {
        public InputOrders()
        {
            this.InputOrderItem = new HashSet<InputOrderItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustumerId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<InputOrderItem> InputOrderItem { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
