//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace join
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputOrderItem
    {
        public int Id { get; set; }
        public Nullable<int> OutputOrderId { get; set; }
        public Nullable<int> PackegeId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
    
        public virtual OutputOrders OutputOrders { get; set; }
        public virtual Packeges Packeges { get; set; }
    }
}
