//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace join
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packeges
    {
        public Packeges()
        {
            this.InputOrderItem = new HashSet<InputOrderItem>();
            this.OutputOrderItem = new HashSet<OutputOrderItem>();
            this.Prices = new HashSet<Prices>();
            this.WarehouseItem = new HashSet<WarehouseItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> VolumeMeasureID { get; set; }
        public Nullable<int> MeasureID { get; set; }
    
        public virtual ICollection<InputOrderItem> InputOrderItem { get; set; }
        public virtual Measures Measures { get; set; }
        public virtual Measures Measures1 { get; set; }
        public virtual ICollection<OutputOrderItem> OutputOrderItem { get; set; }
        public virtual Products Products { get; set; }
        public virtual ICollection<Prices> Prices { get; set; }
        public virtual ICollection<WarehouseItem> WarehouseItem { get; set; }
    }
}
