//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ILowLevelKeyboardListener")]
    public interface ILowLevelKeyboardListener {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelKeyboardListener/HookKeyboard", ReplyAction="http://tempuri.org/ILowLevelKeyboardListener/HookKeyboardResponse")]
        void HookKeyboard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelKeyboardListener/HookKeyboard", ReplyAction="http://tempuri.org/ILowLevelKeyboardListener/HookKeyboardResponse")]
        System.Threading.Tasks.Task HookKeyboardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelKeyboardListener/UnHookKeyboard", ReplyAction="http://tempuri.org/ILowLevelKeyboardListener/UnHookKeyboardResponse")]
        void UnHookKeyboard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelKeyboardListener/UnHookKeyboard", ReplyAction="http://tempuri.org/ILowLevelKeyboardListener/UnHookKeyboardResponse")]
        System.Threading.Tasks.Task UnHookKeyboardAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILowLevelKeyboardListenerChannel : global::Client.ServiceReference.ILowLevelKeyboardListener, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LowLevelKeyboardListenerClient : System.ServiceModel.ClientBase<global::Client.ServiceReference.ILowLevelKeyboardListener>, global::Client.ServiceReference.ILowLevelKeyboardListener {
        
        public LowLevelKeyboardListenerClient() {
        }
        
        public LowLevelKeyboardListenerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LowLevelKeyboardListenerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LowLevelKeyboardListenerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LowLevelKeyboardListenerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void HookKeyboard() {
            base.Channel.HookKeyboard();
        }
        
        public System.Threading.Tasks.Task HookKeyboardAsync() {
            return base.Channel.HookKeyboardAsync();
        }
        
        public void UnHookKeyboard() {
            base.Channel.UnHookKeyboard();
        }
        
        public System.Threading.Tasks.Task UnHookKeyboardAsync() {
            return base.Channel.UnHookKeyboardAsync();
        }
    }
}
