//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputOrders
    {
        public InputOrders()
        {
            this.InputOrderItems = new HashSet<InputOrderItems>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public decimal Cost { get; set; }
        public int StatusId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<InputOrderItems> InputOrderItems { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
