//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BS_3VEntities : DbContext
    {
        public BS_3VEntities()
            : base("name=BS_3VEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<InputOrderItems> InputOrderItems { get; set; }
        public virtual DbSet<InputOrders> InputOrders { get; set; }
        public virtual DbSet<Measures> Measures { get; set; }
        public virtual DbSet<OutputOrderItems> OutputOrderItems { get; set; }
        public virtual DbSet<OutputOrders> OutputOrders { get; set; }
        public virtual DbSet<Packages> Packages { get; set; }
        public virtual DbSet<Prices> Prices { get; set; }
        public virtual DbSet<Producers> Producers { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<WareHouseItems> WareHouseItems { get; set; }
        public virtual DbSet<WareHouses> WareHouses { get; set; }
    }
}
