//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _001_Entity_table_splitting
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetails
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
