//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Proxy.ServiceNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNS.IGetDiskInfo")]
    public interface IGetDiskInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDiskInfo/FreeSpace", ReplyAction="http://tempuri.org/IGetDiskInfo/FreeSpaceResponse")]
        string FreeSpace(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDiskInfo/FreeSpace", ReplyAction="http://tempuri.org/IGetDiskInfo/FreeSpaceResponse")]
        System.Threading.Tasks.Task<string> FreeSpaceAsync(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDiskInfo/TotalSpace", ReplyAction="http://tempuri.org/IGetDiskInfo/TotalSpaceResponse")]
        string TotalSpace(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDiskInfo/TotalSpace", ReplyAction="http://tempuri.org/IGetDiskInfo/TotalSpaceResponse")]
        System.Threading.Tasks.Task<string> TotalSpaceAsync(string diskName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDiskInfoChannel : Client_Proxy.ServiceNS.IGetDiskInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDiskInfoClient : System.ServiceModel.ClientBase<Client_Proxy.ServiceNS.IGetDiskInfo>, Client_Proxy.ServiceNS.IGetDiskInfo {
        
        public GetDiskInfoClient() {
        }
        
        public GetDiskInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDiskInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDiskInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDiskInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FreeSpace(string diskName) {
            return base.Channel.FreeSpace(diskName);
        }
        
        public System.Threading.Tasks.Task<string> FreeSpaceAsync(string diskName) {
            return base.Channel.FreeSpaceAsync(diskName);
        }
        
        public string TotalSpace(string diskName) {
            return base.Channel.TotalSpace(diskName);
        }
        
        public System.Threading.Tasks.Task<string> TotalSpaceAsync(string diskName) {
            return base.Channel.TotalSpaceAsync(diskName);
        }
    }
}
