//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookmarksHolderEntities : DbContext
    {
/// <summary>
/// 
/// </summary>
        private static BookmarksHolderEntities instance = null;

        public static BookmarksHolderEntities Instance
        {
            get
            {
                if (instance == null)
                    instance = new BookmarksHolderEntities();

                return instance;
            }
        }
/// <summary>
/// 
/// </summary>

        public BookmarksHolderEntities()
            : base("name=BookmarksHolderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Users> Users { get; set; }
    }
}
