//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure
    {
        public Measure()
        {
            this.Packages = new HashSet<Package>();
            this.Packages1 = new HashSet<Package>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SmallName { get; set; }
    
        public virtual ICollection<Package> Packages { get; set; }
        public virtual ICollection<Package> Packages1 { get; set; }
    }
}
