//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNS.IPrintSomething")]
    public interface IPrintSomething {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintSomething/PrintSomething_Responce", ReplyAction="http://tempuri.org/IPrintSomething/PrintSomething_ResponceResponse")]
        void PrintSomething_Responce(string tmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintSomething/PrintSomething_Responce", ReplyAction="http://tempuri.org/IPrintSomething/PrintSomething_ResponceResponse")]
        System.Threading.Tasks.Task PrintSomething_ResponceAsync(string tmp);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPrintSomething/PrintSomething_OneWay")]
        void PrintSomething_OneWay(string tmp);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPrintSomething/PrintSomething_OneWay")]
        System.Threading.Tasks.Task PrintSomething_OneWayAsync(string tmp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrintSomethingChannel : Client.ServiceNS.IPrintSomething, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintSomethingClient : System.ServiceModel.ClientBase<Client.ServiceNS.IPrintSomething>, Client.ServiceNS.IPrintSomething {
        
        public PrintSomethingClient() {
        }
        
        public PrintSomethingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintSomethingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintSomethingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintSomethingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PrintSomething_Responce(string tmp) {
            base.Channel.PrintSomething_Responce(tmp);
        }
        
        public System.Threading.Tasks.Task PrintSomething_ResponceAsync(string tmp) {
            return base.Channel.PrintSomething_ResponceAsync(tmp);
        }
        
        public void PrintSomething_OneWay(string tmp) {
            base.Channel.PrintSomething_OneWay(tmp);
        }
        
        public System.Threading.Tasks.Task PrintSomething_OneWayAsync(string tmp) {
            return base.Channel.PrintSomething_OneWayAsync(tmp);
        }
    }
}
