//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouses
    {
        public WareHouses()
        {
            this.WareHouseItems = new HashSet<WareHouseItems>();
        }
    
        public int Id { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<WareHouseItems> WareHouseItems { get; set; }
    }
}
