//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouseItems
    {
        public int Id { get; set; }
        public int WareHouseId { get; set; }
        public int PackageId { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Packages Packages { get; set; }
        public virtual WareHouses WareHouses { get; set; }
    }
}
