//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbstractFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masseges
    {
        public int ID { get; set; }
        public string Messages { get; set; }
        public Nullable<System.DateTime> Data_Today { get; set; }
    }
}
