//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public string OwnerName { get; set; }
        public string OwnerSurname { get; set; }
        public string CarModel { get; set; }
        public string CarNumber { get; set; }
    }
}
