// <auto-generated />
namespace DataModel.VisitCardContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RolesAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RolesAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201509011703406_RolesAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
