//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization_mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string LoginName { get; set; }
        public string Pasword { get; set; }
        public string Token { get; set; }
        public string PasHash { get; set; }
        public string Sult { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    }
}
