//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.ServiceNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNS.IMyMath")]
    public interface IMyMath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/Add", ReplyAction="http://tempuri.org/IMyMath/AddResponse")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/Add", ReplyAction="http://tempuri.org/IMyMath/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/Divide", ReplyAction="http://tempuri.org/IMyMath/DivideResponse")]
        int Divide(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/Divide", ReplyAction="http://tempuri.org/IMyMath/DivideResponse")]
        System.Threading.Tasks.Task<int> DivideAsync(int x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyMathChannel : client.ServiceNS.IMyMath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMathClient : System.ServiceModel.ClientBase<client.ServiceNS.IMyMath>, client.ServiceNS.IMyMath {
        
        public MyMathClient() {
        }
        
        public MyMathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public int Divide(int x) {
            return base.Channel.Divide(x);
        }
        
        public System.Threading.Tasks.Task<int> DivideAsync(int x) {
            return base.Channel.DivideAsync(x);
        }
    }
}
