//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measures
    {
        public Measures()
        {
            this.Packeges = new HashSet<Packeges>();
            this.Packeges1 = new HashSet<Packeges>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SmallName { get; set; }
    
        public virtual ICollection<Packeges> Packeges { get; set; }
        public virtual ICollection<Packeges> Packeges1 { get; set; }
    }
}
