//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Packeges = new HashSet<Packeges>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProducerId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Categorys Categorys { get; set; }
        public virtual ICollection<Packeges> Packeges { get; set; }
        public virtual Producers Producers { get; set; }
    }
}
