<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CustomerList.aspx.cs" Inherits="_03_VisitCardViewer.CustomerProfile.CustomerList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Links" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Scripts" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="body" runat="server">

    <asp:ObjectDataSource runat="server" ID="odsCustomers" 
        SelectMethod="GetAll"  
        DeleteMethod="Delete"
        DataObjectTypeName="DataModel.CustomerProfile"
        TypeName="DataAccess.Concrete.DbStore"
        ></asp:ObjectDataSource>

    <asp:Button runat="server" Text="Add" Id="btnAddCustomer" OnClick="btnAddCustomer_Click" />
    <asp:GridView runat="server" ID="dgCustomers" DataSourceID="odsCustomers" DataKeyNames="Id" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" >
        <Columns>
            <asp:BoundField HeaderText="Customer Name" DataField="Name" />
            <asp:BoundField HeaderText="Customer Surname" DataField="Surname" />
            <asp:BoundField HeaderText="Customer Birthday" DataField="Birthday" />
            <asp:BoundField HeaderText="Customer Phone" DataField="Phone" />
            <asp:TemplateField HeaderText="Email">
                <ItemTemplate>
                    <span style="color: green"><asp:Label runat="server" Text='<%#Eval("Email") %>'></asp:Label></span>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
