//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessages
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserNameFrom { get; set; }
        public string UserNameTo { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsSend { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
