//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.AllMessages = new HashSet<AllMessages>();
            this.PrivateMessages = new HashSet<PrivateMessages>();
            this.PrivateMessages1 = new HashSet<PrivateMessages>();
        }
    
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string UserName { get; set; }
        public string UserPasswordHash { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> ExpirienceDate { get; set; }
    
        public virtual ICollection<AllMessages> AllMessages { get; set; }
        public virtual ICollection<PrivateMessages> PrivateMessages { get; set; }
        public virtual ICollection<PrivateMessages> PrivateMessages1 { get; set; }
    }
}
