//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace add_categories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorys
    {
        public Categorys()
        {
            this.Categorys1 = new HashSet<Categorys>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<Categorys> Categorys1 { get; set; }
        public virtual Categorys Categorys2 { get; set; }
    }
}
